AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Telnyx SMS/MMS Gateway (API Gateway -> Lambda -> Secrets Manager -> Telnyx) v1.1

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 15
    MemorySize: 512

Parameters:
  TelnyxSecretId:
    Type: String
    Default: Telnyx-1
    Description: Secrets Manager secret name containing TELNYX_API_KEY
  InternalGatewayToken:
    Type: String
    NoEcho: true
    Description: Shared secret used by your Express server to call this gateway
  SupabaseUrl:
    Type: String
    Description: Supabase project URL (e.g. https://xxx.supabase.co)
  SupabaseServiceKey:
    Type: String
    NoEcho: true
    Description: Supabase service role key (server-side only)

Resources:
  MessagesApi:
    Type: AWS::Serverless::HttpApi

  SendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handler.handler
      Environment:
        Variables:
          TELNYX_SECRET_ID: !Ref TelnyxSecretId
          INTERNAL_GATEWAY_TOKEN: !Ref InternalGatewayToken
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TelnyxSecretId}*

      Events:
        SendSms:
          Type: HttpApi
          Properties:
            ApiId: !Ref MessagesApi
            Path: /sendSMS
            Method: POST
        SendMms:
          Type: HttpApi
          Properties:
            ApiId: !Ref MessagesApi
            Path: /sendMMS
            Method: POST

  BurstSendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/burstHandler.handler
      Timeout: 120
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
          INTERNAL_GATEWAY_TOKEN: !Ref InternalGatewayToken
      Events:
        SendBurstSms:
          Type: HttpApi
          Properties:
            ApiId: !Ref MessagesApi
            Path: /sendBurstSMS
            Method: POST

  HandleBurstInboundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/inboundBurstHandler.handler
      Timeout: 25
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
          INTERNAL_GATEWAY_TOKEN: !Ref InternalGatewayToken
      Events:
        InboundBurst:
          Type: HttpApi
          Properties:
            ApiId: !Ref MessagesApi
            Path: /inbound-burst
            Method: POST

Outputs:
  ApiUrl:
    Description: Base URL for the HTTP API
    Value: !Sub "https://${MessagesApi}.execute-api.${AWS::Region}.amazonaws.com"
